2022 update
jepa/ubcdown pull request #5
Opened 2022-02-28 19:00 UTC by wvictor14

Hi @jepa 

Thank you for making an amazing UBC thesisdown template. I am happy to report that I've successfully used it to write my thesis (just defended!). 

In this pull request, I plan to merge some of the formatting changes that I had to make when UBC-FOGS reviewed my thesis. The goal is for this pull request to fully satisfy the 2022 formatting requirements.

I am going to add to the list of changes here for easy tracking:

- [x]  Change title of table of contents from "Contents" to "Table of Contents" #96cef6fba898e73ca22342020d4fbb6478e139d0
- [x]  Add ["Additional Supervisory Committee Members"](https://www.grad.ubc.ca/current-students/dissertation-thesis-preparation/preliminary-pages) section to committee form #70de7a66bcf3bd01e00356190e91eb09fa0266a2

- [ ]

2022-03-02 07:50 UTC, jepa requested changes
These all look good @wvictor14 , thank you for contributing. Can you change the couple of things I highlighted here?

2022-03-02 07:50 UTC, jepa commented on README.md
> +Note that this template was created and tested using `R version 4.1.1 (2021-08-10) -- "Eggshell Igloo"`.
Please do not erased the versions but add them.

2022-03-02 07:50 UTC, jepa commented on main_script.Rmd
> +csl: ./References/reference_format-Vancouver.csl
Should change name to "reference_format_vancouver.csl" for consistency

2022-03-21 09:10 UTC, merged

2022-03-21 19:44 UTC, wvictor14 commented
Thanks @jepa I'm awaiting UBC to get back to me on a review of my thesis format. I will make any additional changes they suggest to this branch and reopen the PR if needed. 

Victor